// This file is auto-generated by: npm run db:types
// Run `supabase gen types typescript --local > src/types/database.ts` after migrations.
// Placeholder until local Supabase is running.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      houses: {
        Row: {
          id: string;
          name_en: string;
          name_ml: string | null;
          location: string | null;
          description: string | null;
          cover_photo: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_ml?: string | null;
          location?: string | null;
          description?: string | null;
          cover_photo?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_ml?: string | null;
          location?: string | null;
          description?: string | null;
          cover_photo?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      persons: {
        Row: {
          id: string;
          name_en: string;
          name_ml: string | null;
          gender: 'male' | 'female' | 'other' | 'unknown';
          birth_date: string | null;
          birth_date_approx: boolean;
          death_date: string | null;
          is_alive: boolean;
          biography_en: string | null;
          biography_ml: string | null;
          profile_photo: string | null;
          house_id: string | null;
          generation_number: number | null;
          is_root: boolean;
          created_by: string | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_ml?: string | null;
          gender?: 'male' | 'female' | 'other' | 'unknown';
          birth_date?: string | null;
          birth_date_approx?: boolean;
          death_date?: string | null;
          is_alive?: boolean;
          biography_en?: string | null;
          biography_ml?: string | null;
          profile_photo?: string | null;
          house_id?: string | null;
          generation_number?: number | null;
          is_root?: boolean;
          created_by?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_ml?: string | null;
          gender?: 'male' | 'female' | 'other' | 'unknown';
          birth_date?: string | null;
          birth_date_approx?: boolean;
          death_date?: string | null;
          is_alive?: boolean;
          biography_en?: string | null;
          biography_ml?: string | null;
          profile_photo?: string | null;
          house_id?: string | null;
          generation_number?: number | null;
          is_root?: boolean;
          created_by?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'persons_house_id_fkey';
            columns: ['house_id'];
            isOneToOne: false;
            referencedRelation: 'houses';
            referencedColumns: ['id'];
          },
        ];
      };
      relationships: {
        Row: {
          id: string;
          person_a_id: string;
          person_b_id: string;
          relationship_type: 'spouse' | 'biological_child' | 'adopted_child';
          marriage_date: string | null;
          divorce_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          person_a_id: string;
          person_b_id: string;
          relationship_type: 'spouse' | 'biological_child' | 'adopted_child';
          marriage_date?: string | null;
          divorce_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          person_a_id?: string;
          person_b_id?: string;
          relationship_type?: 'spouse' | 'biological_child' | 'adopted_child';
          marriage_date?: string | null;
          divorce_date?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'relationships_person_a_id_fkey';
            columns: ['person_a_id'];
            isOneToOne: false;
            referencedRelation: 'persons';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'relationships_person_b_id_fkey';
            columns: ['person_b_id'];
            isOneToOne: false;
            referencedRelation: 'persons';
            referencedColumns: ['id'];
          },
        ];
      };
      invites: {
        Row: {
          id: string;
          token: string;
          email: string | null;
          created_by: string;
          used_by: string | null;
          status: 'pending' | 'used' | 'expired' | 'revoked';
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          token?: string;
          email?: string | null;
          created_by: string;
          used_by?: string | null;
          status?: 'pending' | 'used' | 'expired' | 'revoked';
          expires_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          token?: string;
          email?: string | null;
          created_by?: string;
          used_by?: string | null;
          status?: 'pending' | 'used' | 'expired' | 'revoked';
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      user_profiles: {
        Row: {
          id: string;
          display_name: string | null;
          is_admin: boolean;
          person_id: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          is_admin?: boolean;
          person_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          is_admin?: boolean;
          person_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pending_changes: {
        Row: {
          id: string;
          change_type: 'add_person' | 'edit_person' | 'add_relationship' | 'remove_relationship';
          status: 'pending' | 'approved' | 'rejected';
          submitted_by: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          target_person_id: string | null;
          payload: Json;
          relationship_payload: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          change_type: 'add_person' | 'edit_person' | 'add_relationship' | 'remove_relationship';
          status?: 'pending' | 'approved' | 'rejected';
          submitted_by: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          target_person_id?: string | null;
          payload: Json;
          relationship_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          change_type?: 'add_person' | 'edit_person' | 'add_relationship' | 'remove_relationship';
          status?: 'pending' | 'approved' | 'rejected';
          submitted_by?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          target_person_id?: string | null;
          payload?: Json;
          relationship_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      recalculate_generations: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: {
      gender_enum: 'male' | 'female' | 'other' | 'unknown';
      change_type_enum: 'add_person' | 'edit_person' | 'add_relationship' | 'remove_relationship';
      change_status_enum: 'pending' | 'approved' | 'rejected';
      relationship_type_enum: 'spouse' | 'biological_child' | 'adopted_child';
      invite_status_enum: 'pending' | 'used' | 'expired' | 'revoked';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
